--- #YAML:1.0
name:                DBQuery
version:             0.001
abstract:            Lib of DB Query
license:             ~
author:              
    - Cnangel <junliang.li@alibaba-inc.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
